# Generated by Django 6.0.3 on 2026-04-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
