# Generated by Django 6.0.3 on 2026-04-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_bank_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='password',
            field=models.CharField(max_length=225),
        ),
    ]
